grpc:
  client:
    config:
      address: "localhost"
      port: 9090
      trust-cert-path: "certs/ca.crt"
      client-cert-path: "certs/client.crt"
      client-key-path: "certs/client.p8.key"

spring:
  main:
    web-application-type: none