grpc:
  server:
    port: 9090
    security:
      enabled: true
      # --- Server's own certificate and key ---
      certificate-chain: "classpath:certs/server.crt"
      private-key: "classpath:certs/server.p8.key"
      # --- Configure mTLS ---
      client-auth: REQUIRE # This enforces client certificate authentication
      trust-cert-collection: "classpath:certs/ca.crt"

server:
  port: 8080